site_name: lpnTPM Documentation
site_url: https://lpntpm.lpnplant.io/
theme:
    name: material
# TODO: provide logo and styling
#     favicon: images/favicon.png
#     logo: images/logo.png
# extra_css:
#     - stylesheets/extra.css
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
    - attr_list
nav:
    - 'About': index.md
    - 'How to':
      - 'Intro': how_to.md
      - 'Building flashing and debugging': building.md
      - 'Running': running.md
    - 'Current issues': issues.md
    - 'TPM modules pinout': TPM_module_Pinout.md
    - 'TPM modules renders': TPM_renders.md
    - 'Journal': journal.md
